### ISSUE TITLE
Applicant field not being filled

### ISSUE THREAD

**Issue by devansh-299** [PS-Division-BITS/TMS#51] opened 2020-02-14 13:18 UTC
**Summary**
When applying for PS to TS or TS to PS transfer the applicant field in the form should already filled in and user should not be allowed to change the data in the field.

**Consequences**
This issue can led to people filling somebody other's transfer application

**Comment by ChetanKhanna** [comment] 2020-02-14 20:56
duplicate of https://github.com/PS-Division-BITS/TMS/issues/47

**Closed as completed by ChetanKhanna** 2020-02-14 20:56 UTC
Labels: duplicate
